// Données aléatoires extraites
export const posterData = {
  titres: [
    "La Nuit des Étoiles",
    "Royaume d'Hiver",
    "L'Éveil du Dragon",
    "Chasseurs de Légendes",
    "Le Grand Mystère",
    "Voyage Intemporel",
    "L'Aube des Héros",
    "Crépuscule Magique",
    "Dernier Refuge",
    "Échappée Sauvage",
    "Les Gardiens de l'Ombre",
    "Renaissance",
    "Le Pacte des Mondes",
    "Horizon Perdu",
    "L'Enfant de Lumière"
  ],
  sous_titres: [
    "Une aventure épique",
    "Le chapitre final",
    "L'histoire commence",
    "Édition collector",
    "Version remasterisée",
    "Le retour",
    "Nouvelle génération",
    "Saga complète",
    "Origines",
    "La légende continue",
    "Chroniques inédites",
    "Adaptation officielle",
    "Univers étendu",
    "Deuxième partie",
    "Trilogie ultime"
  ],
  taglines: [
    "L'aventure ne fait que commencer",
    "Rien ne sera plus jamais pareil",
    "Le destin frappe à votre porte",
    "Une expérience inoubliable",
    "Préparez-vous à l'impossible",
    "Découvrez l'invisible",
    "Quand la magie rencontre le réel",
    "Chaque seconde compte",
    "Au-delà de l'imagination",
    "Ils sont de retour",
    "La fin n'est que le début",
    "Ensemble, tout devient possible",
    "Un monde à découvrir",
    "Plus grand que nature",
    "Laissez-vous transporter"
  ],
  themes: [
    "Epic fantasy adventure",
    "Sci-fi space opera",
    "Dark horror atmosphere",
    "Romantic fairy tale",
    "Action-packed thriller",
    "Mysterious noir detective",
    "Superhero origin story",
    "Post-apocalyptic survival",
    "Period drama historical",
    "Magical Christmas wonder",
    "Halloween spooky fun",
    "Summer blockbuster",
    "Cyberpunk neon future",
    "Western frontier",
    "Underwater exploration"
  ],
  ambiances: [
    "Epic cinematic",
    "Dark moody",
    "Bright vibrant",
    "Soft dreamy",
    "Intense action",
    "Mysterious foggy",
    "Warm nostalgic",
    "Cold winter",
    "Neon cyberpunk",
    "Magical enchanted",
    "Gritty realistic",
    "Whimsical playful",
    "Elegant luxury",
    "Raw rustic",
    "Futuristic metallic"
  ],
  personnages: [
    "Heroic warrior",
    "Hooded figure",
    "Young adventurer",
    "Powerful sorceress",
    "Space explorer",
    "Elegant princess",
    "Battle soldier",
    "Curious child",
    "Wise mentor",
    "Female fighter",
    "Charming rogue",
    "Noble knight",
    "Cybernetic android",
    "Creature guardian",
    "Determined survivor"
  ],
  environnements: [
    "Castle ruins",
    "Alien planet",
    "Abandoned city",
    "Enchanted forest",
    "Space station",
    "Snowy mountain",
    "Tropical island",
    "Crystal cavern",
    "Medieval village",
    "Cyberpunk alley",
    "Desert wasteland",
    "Underwater ruins",
    "Sky islands",
    "Volcanic eruption",
    "Mystical temple"
  ],
  actions: [
    "Heroic stance",
    "Running motion",
    "Looking back",
    "Reaching out",
    "Leaping air",
    "Facing enemy",
    "Casting spell",
    "High speed",
    "Climbing cliff",
    "Romantic embrace",
    "Combat stance",
    "Discovering artifact",
    "Protecting someone",
    "Emerging explosion",
    "Dramatic silhouette"
  ],
  palettes: [
    "Warm sunset",
    "Cool blue",
    "Purple pink",
    "Golden black",
    "Emerald silver",
    "Blood red",
    "Pastel rainbow",
    "Monochrome blue",
    "Bronze copper",
    "Neon electric",
    "Earth tones",
    "Icy white",
    "Royal purple",
    "Crimson black",
    "Seafoam coral"
  ],
  styles_titre: [
    "Dripping horror",
    "Neon tubes",
    "Frosted glass",
    "Carved wood",
    "Engraved steel",
    "Bubbly cartoon",
    "Jagged blood",
    "Gemstone facets",
    "Weathered stone",
    "Burning fire",
    "Water texture",
    "Polished gold",
    "Spray paint",
    "Holographic digital",
    "Gothic metal",
    "Molded clay",
    "Paper cut",
    "Cosmic nebula",
    "Steampunk brass",
    "Glitch corrupted"
  ],
  details: [
    "Light rays",
    "Dust particles",
    "Magic sparkles",
    "Falling snow",
    "Swirling mist",
    "Lens flares",
    "Fire embers",
    "Glowing runes",
    "Paper leaves",
    "Atmospheric smoke",
    "Light streaks",
    "Heat distortion",
    "Crystal reflections",
    "Ghostly wisps",
    "Motion blur"
  ],
  themes_full: [
    "Epic fantasy adventure",
    "Sci-fi space opera",
    "Dark horror atmosphere",
    "Romantic fairy tale",
    "Action-packed thriller",
    "Mysterious noir detective",
    "Superhero origin story",
    "Post-apocalyptic survival",
    "Period drama historical",
    "Magical Christmas wonder",
    "Halloween spooky fun",
    "Summer blockbuster",
    "Cyberpunk neon future",
    "Western frontier",
    "Underwater exploration"
  ],
  ambiances_full: [
    "epic dramatic cinematic lighting",
    "dark moody atmospheric shadows",
    "bright colorful vibrant energy",
    "soft dreamy ethereal glow",
    "intense action-packed dynamic",
    "mysterious foggy suspenseful",
    "warm golden nostalgic",
    "cold blue winter frost",
    "neon-lit cyberpunk night",
    "magical sparkles enchanted",
    "gritty realistic texture",
    "whimsical playful cartoon",
    "elegant sophisticated luxury",
    "raw rustic natural",
    "futuristic sleek metallic"
  ],
  personnages_full: [
    "heroic warrior in armor",
    "mysterious hooded figure",
    "young adventurer with backpack",
    "powerful sorceress casting spell",
    "rugged space explorer",
    "elegant princess in gown",
    "battle-worn soldier",
    "curious child protagonist",
    "wise old mentor",
    "fierce female fighter",
    "charming rogue thief",
    "noble knight on horseback",
    "cybernetic android",
    "mystical creature guardian",
    "determined survivor"
  ],
  environnements_full: [
    "ancient castle ruins at sunset",
    "vast alien planet landscape",
    "dark abandoned city streets",
    "enchanted forest with glowing trees",
    "futuristic space station interior",
    "snowy mountain peak",
    "tropical island paradise",
    "underground cavern with crystals",
    "medieval village marketplace",
    "neon-lit cyberpunk alley",
    "desert wasteland with ruins",
    "underwater city ruins",
    "floating sky islands",
    "volcanic eruption background",
    "mystical temple entrance"
  ],
  actions_full: [
    "standing heroically with weapon raised",
    "running towards camera in slow motion",
    "looking back over shoulder dramatically",
    "reaching out hand towards viewer",
    "leaping through the air",
    "facing off against unseen enemy",
    "casting magical spell with glowing hands",
    "riding vehicle at high speed",
    "climbing dangerous cliff",
    "embracing in romantic pose",
    "wielding dual weapons in combat stance",
    "discovering ancient artifact",
    "protecting someone behind them",
    "emerging from explosion",
    "silhouetted against dramatic sky"
  ],
  palettes_full: [
    "warm orange and red sunset tones",
    "cool blue and teal night palette",
    "vibrant purple and pink gradient",
    "golden yellow and deep black contrast",
    "emerald green and silver highlights",
    "blood red and dark grey shadows",
    "pastel rainbow soft colors",
    "monochromatic blue scale",
    "bronze and copper metallic",
    "neon cyan and magenta electric",
    "earth tones brown and beige",
    "icy white and pale blue",
    "royal purple and gold luxury",
    "crimson red and pitch black",
    "seafoam green and coral pink"
  ],
  styles_titre_full: [
    "dripping horror lettering, torn edges, glossy red liquid texture, glowing sinister vibe",
    "bright neon tube letters, electric glow, slight chromatic aberration, futuristic vaporwave look",
    "frosted glass letters, icy texture, translucent frozen edges, cold blue inner glow",
    "hand-carved wooden lettering, deep grooves, warm grain texture, rustic fantasy aesthetic",
    "polished engraved steel letters, sharp reflections, industrial sci-fi shine",
    "rounded bubbly cartoon letters, colorful shading, outlined comic look",
    "sharp jagged letters, blood splatter texture, rough grain, violent horror tone",
    "faceted gemstone letters, prism reflections, diamond-like clarity, luminous highlights",
    "weathered carved stone letters, cracks, moss details, archaeological fantasy mood",
    "burning fire lettering, glowing embers, smoke trails, intense heat distortion",
    "transparent water-textured letters, droplets, soft reflections, fluid organic movement",
    "polished gold lettering, embossed texture, warm specular highlights, luxury vibe",
    "spray-painted lettering, rough outlines, dripping paint, street-art graffiti style",
    "holographic translucent letters, digital flicker, refraction effects, sci-fi projection",
    "blackletter-inspired carved metal, dark engraved texture, dramatic gothic atmosphere",
    "hand-molded clay letters, fingerprint texture, soft studio lighting, claymation charm",
    "layered paper-cut letters, soft shadows, handcrafted collage feel",
    "letters filled with nebula textures, stars, glowing cosmic colors, ethereal space vibe",
    "aged brass letters, rivets, gears, Victorian industrial steampunk detailing",
    "distorted corrupted letters, RGB glitch separation, pixel noise, digital malfunction look"
  ],
  details_full: [
    "volumetric light rays",
    "floating dust particles",
    "magical sparkles and glitter",
    "falling snow or rain",
    "swirling mist and fog",
    "lens flares and light leaks",
    "fire embers rising",
    "glowing runes or symbols",
    "scattered paper or leaves",
    "atmospheric smoke",
    "trailing light streaks",
    "shimmering heat distortion",
    "crystalline reflections",
    "ethereal ghostly wisps",
    "dynamic motion blur"
  ]
};;